### ISSUE TITLE
Converting UK National Grid to Lat Lon and vice versa

### ISSUE THREAD

**Issue by TimG1964** [anowacki/BritishNationalGrid.jl#8]
I have a UK postcode picked more or less at random: BT3 9DT.
Google tells me this has the following properties:
```
Latitude: 54.6136 / 54°36'49"N
Longitude: -5.8986 / 5°53'54"W
OS Eastings: 335812
OS Northings: 375965
```
I thought I’d try to convert between grid and lat lon, but I can’t get the right answer.
```
using BritishNationalGrid

p1 = BNGPoint(335812, 375965)
println("p1 = ",p1)
println("lonlat(p1) = ", lonlat(p1))
println("BNGpoint = ", BNGPoint(lat=54.613625, lon=-5.898562))
println("BNGPoint = ", BritishNationalGrid.lonlat2bng(-5.898562, 54.613625))
```
I get the results

```
p1 = BNGPoint{Int64}(335812, 375965)
lonlat(p1) = (-2.9640652376747165, 53.27677828095288)
BNGpoint = BNGPoint{Float64}(148376.87358622215, 531260.3815596306)
BNGPoint = (148376.87358622215, 531260.3815596306)
```
What am I doing wrong?

[https://discourse.julialang.org/t/converting-uk-national-grid-to-lat-lon-and-vice-versa/109628](url)

**Comment by anowacki** [comment]
Hi @TimG1964.  What is happening here with your Belfast postcode is that Google is giving you a grid reference on the *Irish* grid.  This is different from the OS's National Grid which applies to Great Britain only—although parts of Belfast are indeed in square NW of the OSGB NG.  So this package is giving you the correct British NG coordinates.

I will close this because the package is designed only for OSGB National Grid references, but I will add a note about the Irish Grid to the readme.
